version: "3"

services:
  postgres:
    image: postgres:14.9-alpine
    environment:
      POSTGRES_DB: 'elo'
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 5s
    ports:
      - 19910:5432
  web:
    build:
      context: .
    volumes:
      - .:/elo
    depends_on:
      - postgres
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://postgres@postgres/elo

volumes:
  postgres-db-volume: